### ISSUE TITLE
Exception in NEOS 8.3.20

### ISSUE THREAD

**Issue by mgrundkoetter** [digital-competence/DigiComp.FlowSymfonyBridge.Messenger#2]
I use the fork of this Repo by Kay Strohbach inside a NEOS 8.3.20 installation. The setup was ok but when I include the messagebus in an action controller, I get an exception:

```
Object with name Symfony\Component\Messenger\EventListener\StopWorkerOnSigtermSignalListener is not an EventSubscriberInterface
Exception Code: 1618753949
Type: RuntimeException
Thrown in File: Data/Temporary/Development/Cache/Code/Flow_Object_Classes/DigiComp_FlowSymfonyBridge_Messenger_EventDispatcherFactory.php
Line: 37
Original File: Packages/Application/DigiComp.FlowSymfonyBridge.Messenger/Classes/EventDispatcherFactory.php
```

I also had to adjust the config as some Symfony classes have been removed/renamed:

```yaml
      eventDispatcher:
        subscribers:
          Symfony\Component\Messenger\EventListener\StopWorkerOnSigtermSignalListener: false

      transportFactories:
        Symfony\Component\Messenger\Transport\InMemoryTransportFactory: ~
        Symfony\Component\Messenger\Transport\InMemory\InMemoryTransportFactory: true
```
